### ISSUE TITLE
Download links are 404

### ISSUE THREAD

**Issue by cpeterso** [cmderdev/cmderdev.github.io#10]
The "Download mini" and "Download full" links on [cmder.net](http://cmder.net/) are 404 because they point to `https://github.com/cmderdev/cmder/releases/download/1.3.1/cmder.zip` but the release URL is `https://github.com/cmderdev/cmder/releases/download/v1.3.1/cmder.zip`, i.e. the version number is `v1.3.1`, not `1.3.1`.

**Comment by ghost** [comment]
fixed in #9
