### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by Stanzilla** [cmderdev/cmderdev.github.io#23]
This now works, 

* https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
* https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by NotActuallyTerry** [comment]
I'd suggest to properly get around to this, as search engines are penalising non-HTTPS sites and more people expect HTTPS to work when writing out URLs

**Comment by John3** [comment]
As stanzilla shared, github now support https with https://letsencrypt.org/ please check the SSL with this site: https://www.ssllabs.com/ssltest/analyze.html?d=cmder.net

**Comment by ErwinOudG** [comment]
if i go to hhtps://cmder.net (with s) there is a certificate but the certificate is linked to *.github.com, 
![cmder_net](https://user-images.githubusercontent.com/32773437/51992065-a4d66680-24ac-11e9-9503-a6b9e4b14cdb.png)
pls get a correct cert

**Comment by samvasko** [comment]
Should start working any moment 🤞

**Comment by samvasko** [comment]
>  Not yet available for your site because the certificate has not finished being issued.
Please allow 24 hours for this process to complete.

Waiting for this to happen

**Comment by samvasko** [comment]
Done

**Comment by Stanzilla** [comment]
Might wanna adjust the links in the repo descriptions etc as well now :)
